[package]
name = "example-project"
version = "0.0.2"

[addresses]
Sender = "0x1"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "367608ab5cf726039ff44bfdac1f2177210b1440"
subdir = "aptos-move/framework/move-stdlib"
addr_subst = { Std = "0x1" }

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "367608ab5cf726039ff44bfdac1f2177210b1440"
subdir = "aptos-move/framework/aptos-framework"
addr_subst = { Std = "0x1" }
