[package]
name = "example-project"
version = "0.0.1"

[addresses]
Sender = "0x1"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "bb3a847c6ae8967661826775cd026f6fdb2abf0c"
subdir = "aptos-move/framework/move-stdlib"
addr_subst = { Std = "0x1" }

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "bb3a847c6ae8967661826775cd026f6fdb2abf0c"
subdir = "aptos-move/framework/aptos-framework"
addr_subst = { Std = "0x1" }
